services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
#    ports: # Not required for docker-compose run
#      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  backend:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - mongo
    ports:
      - ${BACKEND_PORT}:8000
    volumes:
      - ./library_manager:/app
    environment:
      DB_HOST: mongo
      PORT: ${BACKEND_PORT}
      ACCEPT_URL: ${FRONTEND_CONNECTION_PROTOCOL}://${FRONTEND_HOST}:${FRONTEND_PORT}

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:8082
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_CONNECTION_PROTOCOL: ${FRONTEND_CONNECTION_PROTOCOL}
      REACT_APP_HOSTNAME: ${BACKEND_HOST}
      REACT_APP_BACKEND_PORT: ${BACKEND_PORT}
      PORT: ${FRONTEND_PORT}
    stdin_open: true
    links:
      - backend