services:

  mongo:
    image: mongo
    restart: always
#    ports: # Not required for docker-compose run
#      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  app:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 1234:8000
    environment:
      DB_HOST: mongo
      PORT: 8000
