# Generated by Django 2.2.16 on 2020-11-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
