# Generated by Django 2.2.16 on 2020-11-03 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_bookdata_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdata',
            old_name='description',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='published',
        ),
        migrations.RemoveField(
            model_name='bookdata',
            name='submitted',
        ),
        migrations.AddField(
            model_name='bookdata',
            name='author',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='bookdata',
            name='category',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='bookdata',
            name='publisher',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='bookdata',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
